
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_r18.yml',
  './include/rtdetr_r18vd.yml',
]


output_dir: ./output/rtdetr_r18vd_visdrone_p2fusion

PResNet:
  depth: 18
  return_idx: [0, 1, 2, 3]  # Include C2 (index 0) for P2 fusion
  freeze_at: -1
  freeze_norm: False
  pretrained: True

HybridEncoder:
  in_channels: [64, 128, 256, 512]  # Add C2 channels (64 for ResNet-18 with BasicBlock)
  feat_strides: [4, 8, 16, 32]  # Add stride 4 for C2
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100

# VisDrone dataset configuration
epoches: 90
num_classes: 10

train_dataloader:
  batch_size: 4
  dataset:
    ann_file: /kaggle/working/annotations_VisDrone_train_remap.json
    img_folder: /kaggle/input/visdrone-2019-coco-format/train

val_dataloader:
  batch_size: 4
  dataset:
    ann_file: /kaggle/working/annotations_VisDrone_val_remap.json
    img_folder: /kaggle/input/visdrone-2019-coco-format/val

#config for P2 fusion training R18 improvement 1
